第３回動画の課題を提出します
daimyo-college/practice-2020 pull request #3
Opened 2020-09-09 00:45 UTC by tsuyoshi-7863

2020-09-14 05:07 UTC, udzura requested changes

2020-09-14 05:07 UTC, udzura commented on tsuyoshi-7863/README.md
> +　＊学生時代の部活動：サッカー部
ここまで、素晴らしいコミットです。ありがとうございます！

一点追加要望をさせてください。

**個人的に鹿児島のおすすめのお店の情報** をREADMEに追記してください。よろしくお願いいたします！

2020-09-14 21:37 UTC, tsuyoshi-7863 commented on tsuyoshi-7863/README.md
> +　＊学生時代の部活動：サッカー部
さっそく追加してみました！

2020-09-15 02:59 UTC, udzura approved these changes

2020-09-15 02:59 UTC, udzura commented on tsuyoshi-7863/README.md
> +　＊ぶえんかん：我が地元のお店、漁港とれたて伊勢海老
素晴らしい！どのお店も初めて知りました。ぜひチャレンジしたいです

2020-09-15 02:59 UTC, udzura commented
一つのコミットの粒度も完璧です！ 👍 
https://github.com/daimyo-college/practice-2020/pull/3/commits/a47292c6732f7de431401d76e107b6e2b0948634

2020-09-15 07:35 UTC, merged